In [1]:
# import the necessary libraries
import numpy as np
import pandas as pd

## Basic Python

### 1.Split string

In [2]:
per_name= "Hey I am mohammed afridi"
per_name.split()

['Hey', 'I', 'am', 'mohammed', 'afridi']

### 2.Formatted string 
* We can format string by Built in function .format method.

In [3]:
planet = "Earth"
diameter = 12472
print("The diameter of the {planet} is {diameter} kilometers".format(planet=planet, diameter=diameter))

The diameter of the Earth is 12472 kilometers


### 3.Extract hello from nested dictionary

In [4]:
nested_dictionary = {"k1":[1,2,3,
                   {"tricky":["oh","man","inception",
                              {"target":[1,2,3,"hello"]
                              }]}]
            }

print(nested_dictionary["k1"][3]["tricky"][3]["target"][3])

hello


## Numpy

### 4.1 Create an array of zeros

In [5]:
numpy_12 = np.zeros(12)
numpy_12

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 5.Numpy array of all the even integers from 10 to 60 

In [6]:
np_even = np.arange(10,61,2)
np_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60])

### 6. Create a 3x3 matrix 

In [7]:
np_3d = np.arange(0,9).reshape(3,3)
np_3d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 7.Concatenate two array

In [8]:
num1 = np.array([1,2,3])
num2 = np.array([4,5,6])
concatenate = np.concatenate((num1, num2),axis=None)
concatenate

array([1, 2, 3, 4, 5, 6])

### 8.Create a dataframe with 3 rows and 2 columns


In [9]:
rand_num = np.random.randint(10,size=(3,2))
df = pd.DataFrame(rand_num,columns=["row1","row2"])
df

row1  row2
0     9     0
1     0     0
2     0     8

In [10]:
pd_dict = {
    "col_1":[1,2,3],
    "col_2":[2,5,6]
          }
# Create dataframe by dictionary
df = pd.DataFrame(pd_dict)
df

col_1  col_2
0      1      2
1      2      5
2      3      6

In [11]:
# Add dataframe by list 
name_list = ["Prathy",20],["Durai",20],["Karthick",20],["afridi",19]
df = pd.DataFrame(name_list,columns=["Name","Age"])
df

Name  Age
0    Prathy   20
1     Durai   20
2  Karthick   20
3    afridi   19

### 9.Generate series of date from 1st jan 2023 - 10 th feb 2023

In [12]:
# dataframe Generator 
df = pd.DataFrame()

df["time"] = pd.date_range(start ="1/1/2023",end ="2/10/2023",freq ="24H")

df["year"] =df["time"].dt.year
df["month"] = df["time"].dt.month
df["day"] = df["time"].dt.day

In [13]:
df.head()

time  year  month  day
0 2023-01-01  2023      1    1
1 2023-01-02  2023      1    2
2 2023-01-03  2023      1    3
3 2023-01-04  2023      1    4
4 2023-01-05  2023      1    5

### 10. Create 2D list to dataframe

In [14]:
list_2d = [[1,"aaa",22],[2,"bbb",25],[3,"ccc",24]]
df = pd.DataFrame(list_2d,columns=["col1","col2","col3"])
df

col1 col2  col3
0     1  aaa    22
1     2  bbb    25
2     3  ccc    24